### ISSUE TITLE
Cannot createall with Python 3

### ISSUE THREAD

**Issue by KINFOO** [vahidR/restful-todo#3]
Hi,

Running `restful-todo` with _Python 3_ fails:
```bash
$ python manage.py createall
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    app = create_app(os.getenv('FLASK_CONFIG') or 'default')
  File "/home/kevin/Development/restful-todo/app/__init__.py", line 20, in create_app
    from main import main as main_blueprint
ImportError: No module named 'main'
$ python -V
Python 3.4.1
```
Digging virtual environment generation I spotted theses lines:
```sh
$ mkvirtualenv -p $( which python3 ) -a /w/restful-todo -r /w/restful-todo/requirements.txt restfultodo
...
Running setup.py install for Flask-WTF
      File "/home/kevin/.virtualenvs/restfultodo/lib/python3.4/site-packages/flask_wtf/recaptcha/widgets.py", line 17
        _ = lambda(s): s
                  ^
    SyntaxError: invalid syntax
...
```
Did you succeed to run it with _Python 3_?

Kevin

**Comment by vahidR** [comment]
Hi,

It's been developed under python 2.7..

**Comment by whereeaglesdare** [comment]
Install a new version of flask-WTF

> git clone git://github.com/lepture/flask-wtf.git
